### ISSUE TITLE
Failure to load details of records that fail data qualit tests

### ISSUE THREAD

**Issue by adedekris** [datakind/Data-Observation-Toolkit#33] opened 2022-11-09 17:00 UTC
**Describe the bug**
Error on view data for failed tests.

**To Reproduce**
1. Go to Run monitoring -> run log -> view (link under Run results), number (link under Rows_failed) ->view data (under failed tests).
2. See the error .. _UncaughtPromiseRejection: Failed_Test_data_record failed to execute_

**Expected behavior**
The link should load the details of the records that failed the data quality test

**Screenshots**
![image](https://user-images.githubusercontent.com/42243810/200893200-0f8a6006-f47c-463b-9335-44062391d675.png)

**Comment by dividor** [comment] 2022-11-09 22:59
@adedekris, this is an issue specific to the environment there, select permission on the data schema needs to be persisted.  However I raised this issue to tackle the root cause:

https://github.com/datakind/Data-Observation-Toolkit/issues/34

**Comment by dividor** [comment] 2022-12-04 19:17
Local environmental issue related to DB permissions, resolved indirectly.

**Closed** 2022-12-04 19:17 UTC
